-- ============================================================================
-- BACKUP DA VIEW vw_precatorios_full (ANTES DA ATUALIZAÇÃO V2.5.2)
-- Data: 04/12/2025
-- ============================================================================

CREATE OR REPLACE VIEW vw_precatorios_full AS
 SELECT d.cpf,
    d.numero_processo_cnj,
    d.processo_origem,
    d.requerente_caps,
    d.numero_ordem,
    d.vara,
    d.processo_execucao,
    d.processo_conhecimento,
    d.data_ajuizamento,
    d.data_transito_julgado,
    d.data_base_atualizacao,
    d.data_nascimento,
    d.advogado_nome,
    d.advogado_oab,
    d.credor_nome,
    d.credor_cpf_cnpj,
    d.devedor_ente,
    d.banco,
    d.agencia,
    d.conta,
    d.conta_tipo,
    d.tipo_levantamento,
    d.dados_bancarios_advogado,
    d.cpf_titular_conta,
    d.valor_principal_liquido,
    d.valor_principal_bruto,
    d.juros_moratorios,
    d.valor_total_requisitado,
    d.contrib_previdenciaria_iprem,
    d.contrib_previdenciaria_hspm,
    d.valor_compensado,
    d.contribuicao_social,
    d.salario_pericial,
    d.assist_tecnico,
    d.custas,
    d.despesas,
    d.multas,
    d.idoso,
    d.doenca_grave,
    d.pcd,
    d.rejeitado,
    d.motivo_rejeicao,
    d.observacoes,
    d.anomalia,
    d.descricao_anomalia,
    d.process_diagnostico,
    d.caminho_pdf,
    d.timestamp_ingestao,
    d.process_calculo,
    c.fator_ipcae_antes,
    c.fator_ipcae_pos,
    c.fator_juros_2aa_simples,
    c.meses_para_2aa,
    c.principal_original,
    c.principal_apos_antes,
    c.principal_pos_ipca,
    c.principal_final_ipca_2aa,
    c.juros_mora_anteriores_base,
    c.juros_mora_apos_antes,
    c.juros_mora_final_corrigido,
    c.total_corrigido,
    c.criado_em AS data_calculo,
    q.nome_requerente,
    q.email AS email_requerente,
    q.timestamp_consulta AS data_ultima_consulta
   FROM ((esaj_detalhe_processos d
     LEFT JOIN esaj_calc_precatorio_resumo c ON ((((c.cpf)::text = (d.cpf)::text) AND ((c.numero_processo_cnj)::text = (d.numero_processo_cnj)::text))))
     LEFT JOIN ( SELECT DISTINCT ON (consultas_esaj.cpf) consultas_esaj.cpf,
            consultas_esaj.nome_requerente,
            consultas_esaj.email,
            consultas_esaj.timestamp_consulta
           FROM consultas_esaj
          ORDER BY consultas_esaj.cpf, consultas_esaj.timestamp_consulta DESC) q ON (((q.cpf)::text = (d.cpf)::text)));;
